version: 2.1

orbs:
  # aws-ecr: circleci/aws-ecr@7.3.0
  aws-eks: circleci/aws-eks@1.1.0
  kubernetes: circleci/kubernetes@1.0

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    
    # docker:
    #   - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  docker-build:
    docker:
      - image: circleci/node:13.8.0
    
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: build docker container and push tag
          command: |
            docker build -t uda-capstone-${CIRCLE_WORKFLOW_ID} .
            docker image ls
            echo " docker id and image"
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker tag uda-capstone-${CIRCLE_WORKFLOW_ID} ${DOCKER_USERNAME}/uda-capstone-${CIRCLE_WORKFLOW_ID}
            docker push ${DOCKER_USERNAME}/uda-capstone-${CIRCLE_WORKFLOW_ID}
            echo "image pushed"



workflows:
  deployment:
    jobs:
      - lint
      - docker-build:
          requires:
            - lint
