apiVersion: apps/v1
kind: Deployment
metadata:
  name: UdaCapstone
  namespace: UdaCapstone-ns
  labels:
    app: UdaCapstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: UdaCapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: UdaCapstone
    spec:
      containers:
      - name: UdaCapstone
        imagePullPolicy: Always
        image: uda-capstone
        ports:
        - name: http
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

      