apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-capstone
  namespace: uda-capstone-ns
  labels:
    app: uda-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uda-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uda-capstone
    spec:
      containers:
      - name: uda-capstone
        image: myaxu/uda-capstone
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

      