---
apiVersion: v1
kind: Service
metadata:
  name: uda-capstone
  namespace: uda-capstone-ns
  labels:
    app: uda-capstone
spec:
  type: LoadBalancer
  selector:
    app: uda-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80